name: Post welcome comment
 
 # This step triggers after the learner creates a new repository from the template.
 # This workflow updates from step 0 to step 1.
 
 # This will run every time we create push a commit to `main`.
 # Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  pull_request:
    types: [opened]
  push:
     branches:
       - main
 # Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  pull-requests: write
   # Need `contents: read` to checkout the repository.
   # Need `contents: write` to update the step metadata.
jobs:
   build:
    name: Post welcome comment
    runs-on: ubuntu-latest
   # Get the current step to only run the main job when the learner is on the same step.
   
